### ISSUE TITLE
Contact state the wrong way round?

### ISSUE THREAD

**Issue by s0129** [jgow/org.openhab.binding.mqtt.frigatesvr#3]
I was under the impression in Openhab Contact state is:
OPEN = True = ON
CLOSED = False = OFF

I think currently in this binding it is the other way round?
I am seeing when mqtt reports detected motion as OFF, Openhab is displaying OPEN.

**Comment by jgow** [comment]
As an electrical engineer, to me a 'contact' (switch) is usually active when it is closed and current is flowing. (a light is on when you close the switch). Thus, in the binding, when motion is detected, the switch is closed. The inverse logic above doesn't make any sense to me.
