### ISSUE TITLE
URL for current event clip fgEventClipURL

### ISSUE THREAD

**Issue by temuccio** [jgow/org.openhab.binding.mqtt.frigatesvr#6]
Hi, 
I'm trying this binding and I have seen that the string is not correctly for URL for current event clip:
the binding generate this: 
`http://192.168.178.104:5000/events/1709737398.788055-fxohct/clip.mp4`
But the correct string is
`http://192.168.178.104:5000/api/events/1709737398.788055-fxohct/clip.mp4`

I wrong the configuration?

**Comment by jgow** [comment]
Thanks for the report - this should be fixed in v2.0 and in the tree.
